// Loads the real datasheet catalog generated by scripts/sync-data.mjs
// (public/data/catalog.json + meta.json) and provides the points math that
// depends on it. Unit instances in an army are spread-copies of a catalog
// entry (see src/lib/armies.js) plus `instId`/`compositionIndex`/`photo`, so
// points just look up the chosen composition option's fixed cost.

import { withBase } from "./paths.js";
import { getCachedRemote } from "./remoteData.js";

const FACTION_ACCENT = {
  "Space Marines": "#2E4C6D",
  Orks: "#3E5F2E",
  Necrons: "#3D6B5E",
  "Chaos Space Marines": "#6B1F1F",
  Aeldari: "#3A5F7D",
  Tyranids: "#5E1F5E",
  "Adeptus Custodes": "#8E6A1D",
  "Astra Militarum": "#4A5B2E",
  "Death Guard": "#4A5A2E",
};

function hashHue(str) {
  let h = 0;
  for (let i = 0; i < str.length; i++) h = (h * 31 + str.charCodeAt(i)) >>> 0;
  return h % 360;
}

export function factionAccent(faction) {
  if (FACTION_ACCENT[faction]) return FACTION_ACCENT[faction];
  return `hsl(${hashHue(faction || "")}, 35%, 30%)`;
}

export async function fetchCatalog() {
  const [cachedUnits, cachedMeta] = await Promise.all([getCachedRemote("catalog"), getCachedRemote("meta")]);
  if (cachedUnits && cachedMeta) return { units: cachedUnits, meta: cachedMeta };

  const [unitsRes, metaRes] = await Promise.all([
    fetch(withBase("/data/catalog.json")),
    fetch(withBase("/data/meta.json")),
  ]);
  if (!unitsRes.ok) throw new Error("Failed to load catalog data — try `npm run sync-data`.");
  const units = await unitsRes.json();
  const meta = metaRes.ok ? await metaRes.json() : null;
  return { units, meta };
}

export function compositionOption(unit) {
  return (unit.composition && unit.composition[unit.compositionIndex]) || unit.composition?.[0];
}

export function unitPoints(unit) {
  return compositionOption(unit)?.points ?? 0;
}

export function cheapestPoints(catalogEntry) {
  return catalogEntry.composition.reduce((min, c) => Math.min(min, c.points), Infinity);
}

export function armyPoints(army) {
  return army.units.reduce((s, u) => s + unitPoints(u), 0);
}

// Approximate: composition options give a total model count (e.g. "10
// models") but not a per-model-type breakdown for mixed squads (a Boyz mob's
// Boss Nob has more wounds than a trooper), so this uses the primary
// model's Wounds stat times the composition's model count. Close enough for
// a live tracker; not exact for units with mixed profiles.
export function maxWounds(unit) {
  const opt = compositionOption(unit);
  const modelCount = opt ? parseInt(opt.description, 10) : NaN;
  const perModel = Number(unit.models?.[0]?.W) || 1;
  return (Number.isFinite(modelCount) && modelCount > 0 ? modelCount : 1) * perModel;
}

export function currentWounds(unit) {
  const max = maxWounds(unit);
  return unit.woundsRemaining == null ? max : Math.min(unit.woundsRemaining, max);
}

// Unit instances are spread-copies of a catalog entry taken at the moment
// they're added to an army, so they're frozen snapshots — if the catalog
// later gains fields (a new sync-data.mjs run, or just a feature added since
// the unit was added) an existing army's units won't have them. Called
// whenever an army is loaded so units always reflect the current catalog
// (updated stats/points/rules included) while keeping everything that's
// actually about *this instance*, not the datasheet.
const INSTANCE_FIELDS = [
  "instId", "compositionIndex", "photo", "leaderInstId", "enhancementId",
  "woundsRemaining", "customEffects", "weaponSelection",
];

// Catalog ids aren't forever stable — switching data sources (or a source
// renumbering its own ids) changes them outright, which would otherwise
// permanently freeze an existing army's units on their old data (matched
// by id, id no longer exists, "keep the stale copy" below). Name is the
// more durable identity for a real-world datasheet, so it's the fallback
// once an id lookup misses, and the id is implicitly healed to the current
// one since only INSTANCE_FIELDS survive the merge below.
function normalizeUnitName(s) {
  return (s || "")
    .normalize("NFD").replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/['’`´]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export function refreshUnits(units, catalog) {
  const byId = new Map(catalog.map((c) => [c.id, c]));
  const byName = new Map(catalog.map((c) => [normalizeUnitName(c.name), c]));
  return units.map((u) => {
    const fresh = byId.get(u.id) || byName.get(normalizeUnitName(u.name));
    if (!fresh) return u; // genuinely gone upstream — keep the stale copy rather than drop it silently
    const instanceData = {};
    for (const key of INSTANCE_FIELDS) if (key in u) instanceData[key] = u[key];
    if (instanceData.compositionIndex >= fresh.composition.length) {
      instanceData.compositionIndex = fresh.composition.length - 1;
    }
    return { ...fresh, ...instanceData };
  });
}

// Which of the datasheet's weapon profiles this particular unit instance is
// actually equipped with. Wahapedia lists every profile a datasheet can take
// (defaults and swap-in options together) with no structured link back to
// which wargear-option text enables which profile, so unit.weaponSelection
// is the player's own manual choice — undefined means "everything" (the
// unfiltered default, same as before this existed).
export function selectedWeapons(unit) {
  const sel = unit.weaponSelection;
  return {
    ranged: sel ? unit.ranged.filter((w) => sel.ranged.includes(w.name)) : unit.ranged,
    melee: sel ? unit.melee.filter((w) => sel.melee.includes(w.name)) : unit.melee,
  };
}
