// Detachment/enhancement data generated by scripts/sync-data.mjs
// (public/data/detachments.json). See unitMatchesAbility for the matching
// heuristic used to highlight "this might apply to this unit" — it is
// deliberately best-effort (the user explicitly opted into automatic
// matching over manual tagging), so every caller must present matches as
// suggestions to verify, never as certain.

import { withBase } from "./paths.js";

export async function fetchDetachments() {
  const res = await fetch(withBase("/data/detachments.json"));
  if (!res.ok) throw new Error("Failed to load detachment data — try `npm run sync-data`.");
  return res.json();
}

// catalog.json's faction names come from two sources that don't agree on
// Space Marines: 40kdc-data tags generic Adeptus Astartes units
// "Adeptus Astartes" and each chapter separately ("Ultramarines", "Black
// Templars", etc.), while detachments.json (still Wahapedia-only — see
// scripts/sync-data.mjs) files every Space Marines detachment under the
// single umbrella name "Space Marines" regardless of chapter. Treat them
// as one faction for matching purposes so a Black Templars (or generic
// Adeptus Astartes) army still finds its detachments.
const SPACE_MARINES_UMBRELLA = new Set([
  "Adeptus Astartes", "Space Marines", "Ultramarines", "Black Templars", "Blood Angels",
  "Crimson Fists", "Dark Angels", "Deathwatch", "Imperial Fists", "Iron Hands",
  "Raven Guard", "Salamanders", "Space Wolves", "White Scars",
]);

export function detachmentsForFaction(detachments, faction) {
  if (SPACE_MARINES_UMBRELLA.has(faction)) {
    return detachments.filter((d) => SPACE_MARINES_UMBRELLA.has(d.faction));
  }
  return detachments.filter((d) => d.faction === faction);
}

function weaponNames(unit) {
  return [...(unit.ranged || []), ...(unit.melee || [])].map((w) => w.name.toLowerCase());
}

export function unitMatchesAbility(unit, ability) {
  const unitKeywords = new Set((unit.keywords || []).map((k) => k.toUpperCase()));
  if ((ability.matchKeywords || []).some((k) => unitKeywords.has(k))) return true;

  const text = ability.text.toLowerCase();
  return weaponNames(unit).some((name) => {
    if (text.includes(name)) return true;
    return name.split(" ").some((word) => word.length > 4 && text.includes(word));
  });
}
