// Detachment/enhancement data generated by scripts/sync-data.mjs
// (public/data/detachments.json). See unitMatchesAbility for the matching
// heuristic used to highlight "this might apply to this unit" — it is
// deliberately best-effort (the user explicitly opted into automatic
// matching over manual tagging), so every caller must present matches as
// suggestions to verify, never as certain.

import { withBase } from "./paths.js";

export async function fetchDetachments() {
  const res = await fetch(withBase("/data/detachments.json"));
  if (!res.ok) throw new Error("Failed to load detachment data — try `npm run sync-data`.");
  return res.json();
}

export function detachmentsForFaction(detachments, faction) {
  return detachments.filter((d) => d.faction === faction);
}

function weaponNames(unit) {
  return [...(unit.ranged || []), ...(unit.melee || [])].map((w) => w.name.toLowerCase());
}

export function unitMatchesAbility(unit, ability) {
  const unitKeywords = new Set((unit.keywords || []).map((k) => k.toUpperCase()));
  if ((ability.matchKeywords || []).some((k) => unitKeywords.has(k))) return true;

  const text = ability.text.toLowerCase();
  return weaponNames(unit).some((name) => {
    if (text.includes(name)) return true;
    return name.split(" ").some((word) => word.length > 4 && text.includes(word));
  });
}
