// Stratagem data generated by scripts/sync-data.mjs (public/data/stratagems.json):
// `core` — the ~11 universal Core Stratagems every army can use regardless
// of detachment; `byDetachment` — each detachment's own ~6 stratagems,
// keyed by detachment_id (the same id used for army.detachmentId).

import { withBase } from "./paths.js";

export async function fetchStratagems() {
  const res = await fetch(withBase("/data/stratagems.json"));
  if (!res.ok) throw new Error("Failed to load stratagem data — try `npm run sync-data`.");
  return res.json();
}

export function stratagemsForDetachment(stratagems, detachmentId) {
  if (!stratagems || !detachmentId) return [];
  return stratagems.byDetachment[detachmentId] || [];
}
