// Tracks whether the app's bundled data (public/data/catalog.json and
// friends — regenerated by `npm run sync-data` and redeployed) has changed
// since this browser last opened the app, so App.jsx can show a one-time
// "data updated" notice instead of silently refreshing everything. meta.json's
// syncedAt changes on every sync, so it doubles as a version marker — this
// doesn't distinguish "nothing actually changed" syncs from real ones, but
// re-running sync-data always means at least an attempt at fresher data, so
// a false-positive "updated" notice is harmless.

const KEY = "last-seen-data-sync";

export async function checkForDataUpdate(meta) {
  if (!meta?.syncedAt) return false;
  let lastSeen = null;
  try {
    const res = await window.storage.get(KEY);
    lastSeen = res && res.value ? res.value : null;
  } catch { /* treat as first launch */ }
  try {
    await window.storage.set(KEY, meta.syncedAt);
  } catch { /* best effort */ }
  return lastSeen != null && lastSeen !== meta.syncedAt;
}
